eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    
    
# eureka:
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: ${eureka_url:http://172.17.0.2:8761/eureka}
#   instance:
#     hostname: 172.17.0.2
#     prefer-ip-address: true
